name: SimpleTimer
version: '1.2'
main: me.sandrp.simpletimer.Main
author: sandrp
api-version: '1.21'
permissions:
  simpletimer.use:
    description: Allows the player to use the SimpleTimer commands
    default: op